version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always

  frontend:
    build: 
      context: ../frontend/expertosy-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    restart: always

volumes:
  backend_data:
  frontend_data: 